### ISSUE TITLE
dataフォルダファイル格納後

### ISSUE THREAD

**Issue by nobkono** [hamamoto-lab/imageViewer#13]
[
<img width="605" alt="dataフォルダ" src="https://github.com/hamamoto-lab/imageViewer/assets/109330297/f7c4e2c8-996b-44ae-b9cd-90727cc57688">
](url)

dataフォルダに格納後ですが、Streamlit立ち上げ後、"dataディレクトリに正しくファイルがおかれていません！正しくファイルを置いて画面をReloadしてください"とでます。
何度かlocalhostをブラウザ上で立ち上げなおしましたが変わらずでした。

ファイル拡張子がjpgなのが問題でしょうか。
ディレクトリ構造が違うでしょうか。

**Comment by t2ag3** [comment]
Error時に出るファイル命名規則メッセージが間違っていたようです。

正しくは、`_Proc`ではなく、`=Proc`です！
